dev: inital works

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,6 +40,38 @@ jobs:
       - name: Check Deployment Exists
         run: |
           echo '${{ toJSON(secrets) }}'
-          curl --location 'https://api.mdoq.io/v1/sak/deployment/id/${{ inputs.mdoq_instance_id }}/' \
+          DEPLOYMENT=$(curl --silent --location 'https://api.mdoq.io/v1/sak/deployment/id/${{ inputs.mdoq_instance_id }}/' \
             --header 'x-mdoq-auth: ${{ secrets.mdoq_api_key }}' \
-            --header 'Content-Type: application/json'
+            --header 'Content-Type: application/json' \
+            | jq -r '.files."${{ inputs.tag }}"')
+          echo ${DEPLOYMENT}
+          if [ "${DEPLOYMENT}" == "null" ]; then 
+            echo "Unable to find deployment";
+            exit 1;
+          else
+            echo "found deployment"
+            exit 0
+          fi
+      - name: Download Deployment
+        run: |
+          echo '${{ toJSON(secrets) }}'
+          DEPLOYMENT=$(curl --silent --location 'https://api.mdoq.io/v1/sak/deployment/id/${{ inputs.mdoq_instance_id }}/' \
+            --header 'x-mdoq-auth: ${{ secrets.mdoq_api_key }}' \
+            --header 'Content-Type: application/json' \
+            | jq -r '.files."${{ inputs.tag }}"')
+          echo ${DEPLOYMENT}
+          if [ "${DEPLOYMENT}" == "null" ]; then 
+            echo "Unable to find deployment";
+            exit 1;
+          fi
+          
+          DOWNLOAD_URL=$(curl --silent --location 'https://api.mdoq.io/v1/storage/deployment/download/instance-id/${{ inputs.mdoq_instance_id }}/deployment-id/${{ inputs.tag }}' \
+            --header 'x-mdoq-auth: ${{ secrets.mdoq_api_key }}' \
+            --header 'Content-Type: application/json' \
+            | jq -r '.presigned_url')
+          echo "download url: ${DOWNLOAD_URL}"
+
+          wget -O deployment.tgz "'${DOWNLOAD_URL}'"
+
+          ls -lath
+        
